name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest] # ubuntu-latest, macos-latest
        arch: [x64, x86, arm64, arm]
        compiler: [clang, gcc]

    steps:
      - uses: actions/checkout@v2

      - name: Checkout dependencies
        run: git submodule update --init

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest] # ubuntu-latest, macos-latest
        arch: [x64, x86, arm64, arm]

    steps:
      - name: Test
        run: ${{github.workspace}}/build/bin/${{env.BUILD_TYPE}}/unit_test.exe

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0

    needs:
      - build
