name: Doxygen

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate documentation
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: ./docs/Doxyfile

      - name: Test
        run: |
          ls -a
          ls -a docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          destination_dir: ./docs
