name: Doxygen

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate documentation
        uses: mattnotmitt/doxygen-action@v1
        with:
            doxyfile-path: 'docs/Doxyfile'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Docs/html
