name: Premake

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build windows
        if: ${{ runner.os == 'windows' }}
        run: ./scripts/gen_gmake2.bat #&& make # 未知原因错误: 创建目录时报错无法找到要创建的目录, 可能是 premake 生成的是 Windows 文件路径

      - name: Build linux
        if: ${{ runner.os == 'linux' }}
        run: ./scripts/gen_gmake2.sh #&& make all # 还不支持 C++20

      # - name: Get premake5
      #   run: |
      #     wget -qO- https://github.com/premake/premake-core/releases/download/v5.0.0-alpha16/premake-5.0.0-alpha16-linux.tar.gz | \
      #     tar xvz premake5 | \
      #     xargs -I"{}" sudo mv {} /usr/bin
      #
      # - name: Generate makefiles
      #   run: premake5 --file=premake5.lua gmake
      #
      # - name: Get dependencies
      #   run: DEBIAN_FRONTEND=noninteractive sudo apt-get update -yqq --allow-releaseinfo-change -o::Dpkg::Use-Pty=0 && DEBIAN_FRONTEND=noninteractive sudo apt-get install -yqq -o::Dpkg::Use-Pty=0 libopenal-dev build-essential libgl1-mesa-dev libglm-dev libglfw3-dev ocl-icd-opencl-dev libc++abi-dev
      #
      # - name: Build
      #   run: cmake --build .
      ##  run: make all
