name: Review

on: [pull_request]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Optionally generate compile_commands.json

      - uses: ZedThree/clang-tidy-review@v0.10.0
        id: review

      # If there are any comments, fail the check
      - if: steps.review.outputs.total_comments > 0
        run: exit 1
