name: Test

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    name: ${{matrix.os}}
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Checkout dependencies
        run: git submodule update --init

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13

      - name: Configure CMake
        run: cmake -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}}

      - name: Test
        run: cd build && ctest -VV -C ${{env.BUILD_TYPE}}

      - name: Setup coverage report generator (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install gcovr

      - name: Setup coverage report generator (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install OpenCppCoverage -y
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH

      - name: Generate coverage report (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: gcovr -r $GITHUB_WORKSPACE -x $GITHUB_WORKSPACE/build/coverage.out -s -f "${{github.workspace}}\include" -f "${{github.workspace}}\tests" ${{ matrix.platform.gcovr_options }} $GITHUB_WORKSPACE

      - name: Generate coverage report (Windows)
        if: matrix.os == 'windows-latest'
        run: OpenCppCoverage.exe --sources "${{github.workspace}}" --export_type cobertura:report.xml -- "${{github.workspace}}/build/bin/${{env.BUILD_TYPE}}/unit_test.exe"

      - name: Upload coverage report to Codecov (Windows)
        if: matrix.os == 'windows-latest'
        uses: codecov/codecov-action@v2.1.0
        with:
          files: ./report.xml
          fail_ci_if_error: true
