name: Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        type: [debug, release]

    name: ${{matrix.os}}-${{matrix.type}}
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup clang (Windows)
        if: matrix.os == 'windows-latest'
        run: echo "PATH=$PATH:C:/msys64/mingw64/bin" >> $GITHUB_ENV

      - name: Setup ninja (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install ninja-build

      - name: Setup cppkg
        run: cargo install --git https://github.com/ShenMian/cppkg

      - name: Setup coverage report generator (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install gcovr

      - name: Setup coverage report generator (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install OpenCppCoverage -y
          echo "C:/Program Files/OpenCppCoverage" >> $env:GITHUB_PATH

      - name: Build (Debug)
        if: matrix.type == 'debug'
        run: cppkg build

      - name: Build (Release)
        if: matrix.type == 'release'
        run: cppkg build -r

      - name: Test
        run: ${{github.workspace}}/target/${{matrix.type}}/math_unit_test --reporters=junit --out=test_report.xml

      - name: Test reporter
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: tests report (${{matrix.os}}-${{matrix.type}})
          path: ./test_report.xml
          reporter: java-junit

      - name: Benchmark (Release)
        if: matrix.type == 'release'
        run: ${{github.workspace}}/target/${{matrix.type}}/math_unit_test -ns -ts=benchmark

      - name: Generate coverage report (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        # run: gcovr --root "${{github.workspace}}" --filter "${{github.workspace}}/src" --filter "${{github.workspace}}/tests" --cobertura coverage_report.xml # gcovr v5.1
        run: gcovr --root "${{github.workspace}}" --filter "${{github.workspace}}/src" --filter "${{github.workspace}}/tests" --xml coverage_report.xml # gcovr v5.0

      - name: Generate coverage report (Windows)
        if: matrix.os == 'windows-latest'
        run: OpenCppCoverage.exe --sources "${{github.workspace}}" --export_type cobertura:coverage_report.xml -- "${{github.workspace}}/target/${{matrix.build_type}}/math_unit_test.exe"

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          files: ./coverage_report.xml
          fail_ci_if_error: true

      # - name: Upload coverage report to codacy
      #   uses: codacy/codacy-coverage-reporter-action@v1
      #   with:
      #     project-token: f0624e5b55864197a1d909f1bfb12634
      #     coverage-reports: coverage_report.xml
